$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
    samples:
        type: string
    outdir: 
        type: string
    logdir: 
        type: string
    
    resources:
        properties:
            default:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer

            mixcr:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer

            vidjil:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer

required:
    - samples